spring:
    datasource:
        url: "jdbc:postgresql://localhost:5432/videodb"
        username: username
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        generate-ddl: true